project_id = "xrqtjblsglcdrfwzcbit"

[functions.analyze-comparison]
verify_jwt = true

[functions.create-user-account]
verify_jwt = true

[functions.generate-analysis]
verify_jwt = true

[functions.process-bioimpedance]
verify_jwt = true

[functions.process-bioimpedance-v2]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true
